import json
import os

from dotenv import load_dotenv
import google.generativeai as genai

from models import AIReport

load_dotenv()

genai.configure(
    api_key=os.getenv("GEMINI_API_KEY")
)





def build_evidence_summary(analysis):
    return f"""
OVERALL SCORE:
{analysis["overall_score"]}

DOCUMENTATION SCORE:
{analysis["documentation"]["score"]}

DOCUMENTATION EVIDENCE:
{analysis["documentation"]["evidence"]}

ORGANIZATION SCORE:
{analysis["organization"]["score"]}

ORGANIZATION EVIDENCE:
{analysis["organization"]["evidence"]}

DEVELOPMENT SCORE:
{analysis["development"]["score"]}

DEVELOPMENT EVIDENCE:
{analysis["development"]["evidence"]}

PROJECT READINESS SCORE:
{analysis["project_readiness"]["score"]}

PROJECT READINESS EVIDENCE:
{analysis["project_readiness"]["evidence"]}
"""

def build_prompt(evidence_summary):
    return f"""
You are a senior software engineer reviewing a GitHub repository.

The scores were already generated by a deterministic evaluation system.

IMPORTANT RULES:

- Do not generate scores.
- Do not modify scores.
- Do not contradict scores.
- Use only the evidence provided.
- Every recommendation must be actionable.
- Do NOT use markdown formatting of any kind inside string values (no **, no *, no backticks)
- Plain text only in all fields

Provide JSON only.

JSON Schema:

{{
    "summary": "string",
    "strengths": ["string"],
    "weaknesses": ["string"],
    "recommendations": ["string"]
}}

Repository Analysis:

{evidence_summary}
"""

def generate_report(analysis):

    evidence_summary = build_evidence_summary(
        analysis
    )

    prompt = build_prompt(
        evidence_summary
    )

    model = genai.GenerativeModel(
        "gemini-2.5-flash"
    )

    try:
        response = model.generate_content(
            prompt
        )

        raw = response.text.strip()

        if raw.startswith("```"):
            raw = raw.replace(
                "```json",
                ""
            )
            raw = raw.replace(
                "```",
                ""
            ).strip()

        parsed = json.loads(raw)

        return AIReport(
            summary=parsed["summary"],
            strengths=parsed["strengths"],
            weaknesses=parsed["weaknesses"],
            recommendations=parsed["recommendations"]
        )

    except Exception as e:
        print("AI ERROR:", e)

        return {
            "summary": "AI report unavailable.",
            "strengths": [],
            "weaknesses": [],
            "recommendations": [],
            "error": str(e)
        }