import json
import os

from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()

genai.configure(
    api_key=os.getenv("GEMINI_API_KEY")
)





def build_evidence_summary(analysis):

    scores = analysis["scores"]
    evidence = analysis["evidence"]

    return f"""
OVERALL SCORE:
{scores["overall"]}

DOCUMENTATION SCORE:
{scores["documentation"]}

DOCUMENTATION EVIDENCE:
{evidence["documentation"]}

ORGANIZATION SCORE:
{scores["organization"]}

ORGANIZATION EVIDENCE:
{evidence["organization"]}

DEVELOPMENT PRACTICES SCORE:
{scores["development"]}

DEVELOPMENT PRACTICES EVIDENCE:
{evidence["development"]}

PROJECT READINESS SCORE:
{scores["project_readiness"]}

PROJECT READINESS EVIDENCE:
{evidence["project_readiness"]}
"""

def build_prompt(evidence_summary):
    return f"""
You are a senior software engineer reviewing a GitHub repository.

The scores were already generated by a deterministic evaluation system.

IMPORTANT RULES:

- Do not generate scores.
- Do not modify scores.
- Do not contradict scores.
- Use only the evidence provided.
- Every recommendation must be actionable.
- Do NOT use markdown formatting of any kind inside string values (no **, no *, no backticks)
- Plain text only in all fields

Provide JSON only.

JSON Schema:

{{
    "summary": "string",
    "highlights": ["string"],
    "improvement_areas": ["string"],
    "recommendations": ["string"]
}}

Repository Analysis:

{evidence_summary}
"""

def generate_report(analysis):

    evidence_summary = build_evidence_summary(
        analysis
    )

    prompt = build_prompt(
        evidence_summary
    )

    model = genai.GenerativeModel(
        "gemini-flash-lite-latest"
    )

    try:
        response = model.generate_content(
            prompt
        )

        raw = response.text.strip()

        if raw.startswith("```"):
            raw = raw.replace(
                "```json",
                ""
            )
            raw = raw.replace(
                "```",
                ""
            ).strip()

        parsed = json.loads(raw)

        return {
            "summary": parsed["summary"],
            "highlights": parsed["highlights"],
            "improvement_areas": parsed["improvement_areas"],
            "recommendations": parsed["recommendations"],
        }

    except Exception as e:
        print("AI ERROR:", e)

        return {
            "summary": "AI assessment unavailable.",
            "highlights": [],
            "improvement_areas": [],
            "recommendations": [],
            "error": str(e)
        }